### ISSUE TITLE
Method To Create User Accounts For Testing

### ISSUE THREAD

**Issue by fisher60** [AbandonTech/abandonauth#54]
## Summary
Currently there is no easy way to create a user account locally for testing on AbandonAuth. In the near future we will also want to create unit tests that will require a user account as well.

We should create an endpoint that allows a user account to be created using a password (similar to upcoming developer application logic). This endpoint should not exist nor be accessible in any way in production.

## Acceptance Criteria
- A method exists to create a user account without a 3rd-party OAuth login/any UI elements.
- A JWT can be exchanged with this new account in order to remain logged in during a test session.
- This functionality is not accessible in production

**Comment by Lopkop** [comment]
Can I take this?

**Comment by fisher60** [comment]
Yes please take this one! I have not gotten to it in months, reassigning to you.
