### ISSUE TITLE
Add and utilize Developer Application names

### ISSUE THREAD

**Issue by fisher60** [AbandonTech/abandonauth#75]
## Summary

Developer applications should have a name that can be displayed to users to make it clear what they are for.

## Acceptance Criteria

1. Developer Applications have a `name` field in `schema.prisma` a default should exist for migrating existing developer applications in production
2. The developer application name is displayed along with the UUID on the `/ui/applications` page

**Comment by fisher60** [comment]
@Lopkop could you please comment on this issue when you get a chance so I can assign you?

**Comment by Lopkop** [comment]
@fisher60 Yes, thank you

**Comment by Xithrius** [comment]
It is done
